services:
   web:
      image: nginx
      ports:
         - "8080:80"
   db:
      image: postgres:17
      ports:
         - "6000:5432"
      environment:
         POSTGRES_DB: teste
         POSTGRES_USER: testador
         POSTGRES_PASSWORD: "1234"
      volumes:
         - postgres_data:/var/lib/postgresql/data

volumes:
   postgres_data:
